FROM python:3.8

LABEL maintainer="Peng"

WORKDIR /chatbot-app

COPY ./iot_platform_docs /chatbot-app/iot_platform_docs

COPY ./requirements.txt /chatbot-app/requirements.txt
RUN pip3 install -r requirements.txt

COPY ./api.py /chatbot-app/api.py
COPY ./app.py /chatbot-app/app.py

COPY ./vector_store /chatbot-app/vector_store

# Print the current directory content to debug
RUN ls -la /chatbot-app

# COPY ./run.sh /chatbot-app/run.sh



# RUN chmod +x /chatbot-app/run.sh

CMD ["python3","app.py"]
